[phases.setup]
nixPkgs = ["nodejs_20", "vips", "pkg-config"]

[phases.install]
cmds = ["npm install --ignore-scripts", "npm rebuild sharp --update-binary || true"]

[phases.build]
cmds = ["npx nest build"]

[start]
cmd = "node dist/main"
