api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Custom File Upload Pro – Order Files"
handle = "custom-file-upload-order"
uid = "18ad7b43-7be1-27bc-68fd-e182e3edec323ca0dd31"

  [[extensions.targeting]]
  module = "./src/OrderUploads.tsx"
  target = "admin.order-details.block.render"
