api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "Custom File Upload Pro – Order Files"
handle = "custom-file-upload-order"

  [extensions.targeting]
  module = "./src/OrderUploads.tsx"
  target = "admin.order-details.block.render"
